from icd11 import Icd11Fetcher


def main():
    fetcher = Icd11Fetcher()
    who_fic_foundation_covid19_vaccines_entity = "894585096"
    latest = fetcher.get_latest_release_for_entity(who_fic_foundation_covid19_vaccines_entity)
    descendants = fetcher.get_mms_descendants_for_entity(who_fic_foundation_covid19_vaccines_entity, latest)

    fsh = f'''//
//
// WARNING!
// This file is automatically generated by `/script/icd11/icd11.py`. Do not manually edit.
//
//
Alias: $icd11-mms = http://id.who.int/icd11/mms

ValueSet: ImmunizationCovidIcd11ValueSet
Id: immunization-covid-icd11
Title: "Immunization / COVID / ICD-11"
Description: "Contains ICD-11 MMS codes from the [`{latest}` release](
https://icd.who.int/icdapi/docs2/SupportedClassifications/) that are descendants of `XM68M6` ("COVID-19 Vaccines")."

* ^copyright = "International Classification of Diseases, Eleventh Revision (ICD-11), World Health Organization (WHO) 
2019/2021. <https://icd.who.int/browse11>. Licensed under [Creative Commons Attribution-NoDerivatives 3.0 IGO licence 
(CC BY-ND 3.0 IGO)](https://creativecommons.org/licenses/by-nd/3.0/igo/)."

* ^version = "{latest}"

{fetcher.descendants_to_fsh(descendants)}
'''
    print(fsh)


if __name__ == "__main__":
    main()
