import datetime as dt
import os

from icd11 import Icd11Fetcher


def main():
    fetcher = Icd11Fetcher()
    who_fic_foundation_vaccines_entity = "164949870"
    latest = fetcher.get_latest_release_for_entity(who_fic_foundation_vaccines_entity)
    descendants = fetcher.get_mms_descendants_for_entity(who_fic_foundation_vaccines_entity, latest)

    fsh = f'''//
//
// WARNING!
// This file is automatically generated by `/script/icd11/get_all_vaccine_descendants.py`. Do not manually edit.
//
//
Alias: $icd11-mms = http://id.who.int/icd11/mms

ValueSet: ImmunizationAllIcd11ValueSet
Id: immunization-all-icd11
Title: "Immunization / All / ICD-11"
Description: "Contains ICD-11 MMS codes from the [`{latest}` release](
https://icd.who.int/icdapi/docs2/SupportedClassifications/) that are descendants of the Foundation element `164949870` (\"Vaccines\") according to the [ICD API](https://icd.who.int/icdapi). Generated on {dt.datetime.now().strftime('%Y-%m-%d')}."

* ^copyright = "International Classification of Diseases, Eleventh Revision (ICD-11), World Health Organization (WHO)
2019/2021. <https://icd.who.int/browse11>. Licensed under [Creative Commons Attribution-NoDerivatives 3.0 IGO license
(CC BY-ND 3.0 IGO)](https://creativecommons.org/licenses/by-nd/3.0/igo/)."

* ^version = "{latest}"

{fetcher.descendants_to_fsh(descendants)}
'''

    dirname = os.path.dirname(__file__)
    filename = os.path.join(dirname,
                            f'../../input/fsh/immunization-all-icd11.fsh')

    with open(filename, 'w') as f:
        f.write(fsh)


if __name__ == "__main__":
    main()
