# This script is used by the GitHub Action that builds the website.
# In order to make canonical URIs resolve, we copy pages like `ValueSet-example.html` to
# `ValueSet/example.html`. This will allow the canonical URIs generated by publisher.jar
# to resolve with GitHub Pages.
#
# The .html files generated by the IG Publisher use relative paths, so this script sets a
# <base> tag on the copied pages so they still work.

use strict;
use warnings;
use File::Find;

# Get the directory name from the first argument
my $directory = shift @ARGV;
die "Usage: $0 <directory>\n" unless defined $directory;

# Find HTML files recursively in the specified directory
find(\&process_html_file, $directory);

sub process_html_file {
    my $filename = $_;
    return unless -f $filename && $filename =~ /\.html?$/i;

    # Read the HTML file content
    open(my $fh, '<', $filename) or die "Cannot open file $filename: $!";
    my @lines = <$fh>;
    close($fh);

    # Modify the HTML file content
    my $modified_content = join('', @lines);

    # Add <base> tag to the <head> section
    $modified_content =~ s/(<head\b[^>]*>)/$1\n<base href="https:\/\/terminology.smarthealth.cards">/i;

    # Write the modified content back to the HTML file
    open($fh, '>', $filename) or die "Cannot write to file $filename: $!";
    print $fh $modified_content;
    close($fh);
}