name: Build IG

on:
  push:
    branches: 
      - main
  workflow_dispatch:    

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update the image to the latest publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: curl -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o ./input-cache/publisher.jar --create-dirs

      - name: Run the IG publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: java -jar ./input-cache/publisher.jar publisher -ig .

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }} 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          # keeps gh-pages branch from storing old commits, which balloons size of repo
          force_orphan: true

      # deploy output to sub-directory indicated by the tag or branch that triggered this workflow, used for testing
      # triggered manually by dispatch of selected branch
      # will be overwritten with next deployment to main
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref != 'refs/heads/main' }} 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          destination_dir: ${{ github.ref_name }}
          keep_files: true