name: CVX Update

on:
  schedule:
    - cron: 1 1 1 * *


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: run python script
      run: | 
        python cvx-parsing.py
    - name: checkout branch
      run: |
        git checkout cvx-parsing-update 
    - name: Create pull request

    #https://github.com/marketplace/actions/create-pull-request
    
      uses: peter-evans/create-pull-request@v4
      with:
        branch: create-pull-request/cvx-parsing-update
        team-reviewers: shc-terminology-maintainers

    


  